### ISSUE TITLE
Difficulty adjustment is not fast enough.

### ISSUE THREAD

**Issue by coli** [vertcoin/vertcoin-old#17]
Current difficulty adjustment rate makes it more advantageous for multipool miners versus dedicated vertcoin miners.

For more background, see http://www.digibyte.co/digishield , and http://www.reddit.com/r/dogecoin/comments/207hfb/ann_dogecoin16_its_ready_all_you_need_to_know/

**Comment by Paul-Bradley** [comment]
Not sure I understand this issue - we retarget every block! We also have no large multipools mining VTC at present.

**Comment by coli** [comment]
Yes you retarget every block, but the difficulty change is not fast enough to match the actualy hash rate. You can see it here: https://graph.vertcoin.org/

Thus it's advantageous to mine Vertcoin when the difficulty is below actual hashrate, and then switch to a different coin when the difficulty is above actual hashrate.

If you checkout http://www.coinwarz.com/difficulty-charts/dogecoin-difficulty-charts You'll see their difficulty is now almost an exact match of the instantaneous hashrate.
