### ISSUE TITLE
Localisation broken

### ISSUE THREAD

**Issue by sylvainblot** [vertcoin/vertcoin-old#19]
Hello Guys,

It seems that the localisation system is broken, I tried to use the latest Mac OS release on french mac, and all the loc strings are displayed in English. Even if I use -lang=fr_FR.
Same if I compile with latest source, I'm going to try to solve this.

**Comment by erkmos** [comment]
Thanks for reporting. Currently the translations are not included in the
binary, we'll make sure to include translations for languages with latin
script for upcoming releases (the chinese, japanese etc translations need
to be updated for vertcoin before we can include them).

**Comment by sylvainblot** [comment]
@erkmos Thanks, can you confirm that changes in bitcoin_en.ts are not taken into account ? Seems like the loc system is not working at all, and reference strings are used instead.

**Comment by erkmos** [comment]
Yeah, the translations seem to be ignored entirely. macdeploy doesn't seem to add them at all actually. Seems they all still said Litecoin too, I just updated that at least.

**Comment by sylvainblot** [comment]
cheers, same problem on linux/windows too for me when i compile the code myself.

**Comment by sylvainblot** [comment]
Found out why, too obvious to be seen at first look :)
bitcoin.qrc should refer to .qm not .ts file
Thanks for the support @erkmos

**Comment by erkmos** [comment]
The translations will be enabled in the next release.
