### ISSUE TITLE
Error 4 in compiler 

### ISSUE THREAD

**Issue by alihbuzaid** [vertcoin/vertcoin-old#20]
I had this error while compiling the src in fedora 7 

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See http://bugzilla.redhat.com/bugzilla for instructions.
make: **\* [obj/alert.o] Error 4

**Comment by dayreiner** [comment]
If you're compiling on a cloud instance (particularly Amazon Micro instances), you can quickly run out of available resources. See here for more info:https://litecointalk.org/index.php?topic=2416.0

When I hit this kind of problem compiling, I either just re-run make a few more times to eventually get past where you're getting killed or temporarily increase the instance size. I've had this happen on DO instances as well as Amazon, not much you can do other than keep retrying or add more resources.
