### ISSUE TITLE
Error 1 During make file.

### ISSUE THREAD

**Issue by reesey275** [vertcoin/vertcoin-old#23]
Attempted Compiling on both Debian 7.0.5 and Ubuntu 12.10, 14.04 and received the exact same error on both.

In file included from db.cpp:6:0:
db.h:14:20: fatal error: db_cxx.h: No such file or directory
compilation terminated.
make: **\* [obj/db.o] Error 1

**Comment by erkmos** [comment]
```
sudo add-apt-repository ppa:bitcoin/bitcoin && sudo apt-get update && sudo
apt-get install libdb4.8++-dev
```
