### ISSUE TITLE
Debian 7, GLIBC_2.15, GLIBC_2.14  not found

### ISSUE THREAD

**Issue by poiuty** [vertcoin/vertcoin-old#24]
Hi, binary v0.8.7.1 linux 64.tar
vertcoind -datadir=/root/.vertcoin -daemon
vertcoind: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by vertcoind)
vertcoind: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.14' not found (required by vertcoind)

**Comment by whitj00** [comment]
http://stackoverflow.com/questions/10863613/how-to-upgrade-glibc-from-version-2-13-to-2-15-on-debian
