### ISSUE TITLE
CentOS 6.5 install =[

### ISSUE THREAD

**Issue by justinvforvendetta** [vertcoin/vertcoin-old#27]
Hi guys. Im currently trying to compile/run the vertcoin daemon on my new server. Yesterday, i spent an entire day with a dogecoin dev, and we rewrote the CentOS install. Now it's time to update Vert! and then i will move to the next coin, and help everyone with CentOS start catching up.

I have tried this installation with no luck:
http://pastie.org/8763028

CentOS is a tough one, but lets get this done.

**Comment by justinvforvendetta** [comment]
actually i when i just tried to run it, it said permission denied. any help?

**Comment by justinvforvendetta** [comment]
./vertcoind
bash: ./vertcoind: Permission denied

**Comment by poiuty** [comment]
chmod 755 ./vertcoind

**Comment by poiuty** [comment]
U can just download https://github.com/vertcoin/vertcoin/releases/download/v0.8.7.3/linux_64.zip

wget https://github.com/vertcoin/vertcoin/releases/download/v0.8.7.3/linux_64.zip

unzip linux_64.zip
mv vertcoind to /usr/bin/
chmod 755 /usr/bin/vertcoind
create /root(or user)/.vertcoin/
create config file /root(or user)/.vertcoin/vertcoin.conf

server=1
rpcallowip=127.0.0.1
rpcuser=xxx
rpcpassword=xxxx

and then ./vertcoind start

**Comment by justinvforvendetta** [comment]
@poiuty  thanks for the quick response. i am new to centos, so i believe i am having a problem with glib, and it is because i have already installed 

rpm -q glibc
glibc-2.12-1.132.el6_5.3.x86_64
glibc-2.12-1.132.el6_5.3.i686

when i run vertcoin:
 ./vertcoind
./vertcoind: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./vertcoind)
./vertcoind: /lib64/libc.so.6: version`GLIBC_2.15' not found (required by ./vertcoind)
./vertcoind: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./vertcoind)

how can i acquire what i need without wrecking my necessary glib 2.12 as well?

**Comment by poiuty** [comment]
try to compile from source code
or try install GLIBC_2.15

**Comment by justinvforvendetta** [comment]
this 1.37 boost is not like boost i am used to. normally this would be easier @poiuty 

example, my boost section of compiling daemon normally looks like this (for CentOS):

wget 'https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2'

tar --warning=no-timestamp -xjf boost_1_55_0.tar.bz2

pushd boost_1_55_0

./bootstrap.sh --without-icu

./bjam toolset=gcc threadapi=pthread threading=multi variant=release link=static runtime-link=shared --without-mpi --without-python -sNO_BZIP2=1 --layout=tagged --build-type=complete --prefix="$VERT_STAGE_LOC" $MAKEOPTS -d+2 install

popd

but, there is no bootstrap.sh for this boost 1.37, so i can not ./bootstrap.sh =[
how should i go about this step?
please help?
