### ISSUE TITLE
vertcoin boost 1.37

### ISSUE THREAD

**Issue by justinvforvendetta** [vertcoin/vertcoin-old#28]
this boost 1.37 is not like boost install i am used to. normally this would be easier. (on CentOS)

example, my boost section of compiling daemon normally looks like this (for CentOS):

wget 'https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2'

tar --warning=no-timestamp -xjf boost_1_55_0.tar.bz2

pushd boost_1_55_0

./bootstrap.sh --without-icu

./bjam toolset=gcc threadapi=pthread threading=multi variant=release link=static runtime-link=shared --without-mpi --without-python -sNO_BZIP2=1 --layout=tagged --build-type=complete --prefix="$VERT_STAGE_LOC" $MAKEOPTS -d+2 install

popd

but, there is no bootstrap.sh for this boost 1.37, so i can not ./bootstrap.sh =[
how should i go about this step?
please help?

**Comment by metalicjames** [comment]
Reopen if this is still a problem.
