### ISSUE TITLE
openssl 1.0.1i

### ISSUE THREAD

**Issue by poiuty** [vertcoin/vertcoin-old#29]
It's time to update OpenSSL. 
bitcoin 0.9.3 already use  OpenSSL to 1.0.1i 
https://bitcoin.org/en/release/v0.9.3

**Comment by marshone** [comment]
Agree, I'm working to build specific package for current release of  Centos/Redhat/Fedora/Ubuntu. let me know if you have specific platform you want the specific build.

**Comment by poiuty** [comment]
Do not forget debian ;) 
And it would be nice to eventually add vertcoin on packages.debian.org
