### ISSUE TITLE
secp256k1.h not found

### ISSUE THREAD

**Issue by scratchy** [vertcoin/vertcoin-old#31]
g++ -c -O2 -std=c++0x -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/root/vertcoin/src -I/root/vertcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/root/vertcoin/src/leveldb/include -I/root/vertcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -MMD -MF obj/wallet.d -o obj/wallet.o wallet.cpp
In file included from main.h:13:0,
                 from wallet.h:13,
                 from wallet.cpp:6:
stealth.h:19:23: fatal error: secp256k1.h: File not found.

Also im unable to find this file on my debian packages, how to get it?

**Comment by metalicjames** [comment]
You must first install libsec256pk1 as per the instructions in build-unix.md

sudo apt-get install libgmp-dev
git clone https://github.com/bitcoin/secp256k1.git 
cd secp256k1 
git checkout dc407ed48cc3a26310763f61c9e5564ac2133e74 
./autogen.sh 
./configure 
make 
make install
