### ISSUE TITLE
obj/stealth.o Error 1

### ISSUE THREAD

**Issue by sigwo** [vertcoin/vertcoin-old#35]
While trying to compile from master-0.9.0.1 and Lyra2RE:

g++ -c -O2 -std=c++0x -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/ironman/vertcoin/src -I/home/ironman/vertcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/home/ironman/vertcoin/src/leveldb/include -I/home/ironman/vertcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -MMD -MF obj/stealth.d -o obj/stealth.o stealth.cpp
stealth.cpp: In function ‘bool ec_multiply(ec_point&, const ec_secret&)’:
stealth.cpp:126:70: error: ‘secp256k1_ec_pubkey_tweak_mul’ was not declared in this scope
     return secp256k1_ec_pubkey_tweak_mul(a.data(), a.size(), b.data());
                                                                      ^
stealth.cpp: In function ‘bool ec_tweak_add(ec_point&, const ec_secret&)’:
stealth.cpp:149:70: error: ‘secp256k1_ec_pubkey_tweak_add’ was not declared in this scope
     return secp256k1_ec_pubkey_tweak_add(a.data(), a.size(), b.data());
                                                                      ^
stealth.cpp: In function ‘ec_point secret_to_public_key(const ec_secret&, bool)’:
stealth.cpp:163:23: error: ‘secp256k1_ec_pubkey_create’ was not declared in this scope
             compressed))
                       ^
stealth.cpp: In function ‘bool ec_add(ec_secret&, const ec_secret&)’:
stealth.cpp:280:61: error: ‘secp256k1_ec_privkey_tweak_add’ was not declared in this scope
     return secp256k1_ec_privkey_tweak_add(a.data(), b.data());
                                                             ^
stealth.cpp: In function ‘bool ec_multiply(ec_point&, const ec_secret&)’:
stealth.cpp:127:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
stealth.cpp: In function ‘bool ec_tweak_add(ec_point&, const ec_secret&)’:
stealth.cpp:150:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
stealth.cpp: In function ‘bool ec_add(ec_secret&, const ec_secret&)’:
stealth.cpp:281:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: **\* [obj/stealth.o] Error 1

**Comment by metalicjames** [comment]
Do you have libsecp256k1 installed? And is it the latest from Git?

**Comment by sigwo** [comment]
Yes, I installed libsec during the make process. Continued with the make process and it failed. I rm -rf'ed vertcoin/ and re-cloned to the same issue.

**Comment by metalicjames** [comment]
In the secp256k1.h file that is installed on your system, are there references to "secp256k1_ec_pubkey_tweak_mul" or "secp256k1_ecdsa_pubkey_tweak_mul"?

**Comment by sigwo** [comment]
No. No references to those.

**Comment by sigwo** [comment]
Already did that. I will try again and re-clone :-)

**Comment by sigwo** [comment]
Ok, I reinstalled secp256k1 and had to reinstall boost (my prob, not vertcoin)

sudo apt-get install libgmp-dev
git clone https://github.com/bitcoin/secp256k1.git
cd secp256k1
./autogen.sh
./configure
make
sudo make install

The sudo is key. :100:

**Comment by sigwo** [comment]
Closing as solved.
