### ISSUE TITLE
vertcoind segfaults when configured with 'disablewallet=1' or started with the '-reindex' flag

### ISSUE THREAD

**Issue by ericecook** [vertcoin/vertcoin-old#37]
Hello gents, thanks for your time and effort on this project.

While I've been working to prepare SimpleMulti for the fork I spent a stupid amount of time banging my head against segfaults in the new wallet - thinking they were machine specific or shared library issues.

I've confirmed them with the 0.9.0.1-amd64 binary, and my own compiled code, please let me know if you are unable to replicate.

IMO, these are both pretty important issues to fix, at least for mining. 
- If the block database becomes corrupted and re-indexing is not an option, miners could be forced to wait for the whole chain to download. Obviously this is a PITA for wallet users as well
- Being able to disable the wallet significantly improves the daemon performance, resulting in many fewer orphans.

**Comment by metalicjames** [comment]
Both bugs fixed as of https://github.com/vertcoin/vertcoin/commit/e9d9ef57d959078ea66198eae918b4ecc45eee43

Thanks for the report :)

**Comment by ericecook** [comment]
Awesome, I'll give it a try
