### ISSUE TITLE
Missing separator in makefile.unix ?

### ISSUE THREAD

**Issue by daybyter** [vertcoin/vertcoin-old#40]
Step 14 : RUN cd /vertcoin/src/ && make -f makefile.unix USE_UPNP=-
 ---> Running in ea80f37d4ddb
makefile.unix:234: **\* missing separator.  Stop.
2014/12/21 22:48:50 The command [/bin/sh -c cd /vertcoin/src/ && make -f makefile.unix USE_UPNP=-] returned a non-zero code: 2
Makefile:4: recipe for target 'build' failed
make: **\* [build] Error 1

**Comment by metalicjames** [comment]
Shouldn't USE_UPNP be set to 1 or 0?

**Comment by daybyter** [comment]
Yeah, this could be. I think I used this from the primecoin build. But still the separator is missing as it seems?

https://github.com/vertcoin/vertcoin/blob/master-0.9.0.1/src/makefile.unix#L234

See the indentation?

**Comment by daybyter** [comment]
USE_UPNP=- is better, because you don't need the libs then.

I modified the makefile now locally and it works. I created a docker container to run the wallet.

**Comment by metalicjames** [comment]
Yeah, I see the missing indent, will fix.

**Comment by metalicjames** [comment]
Fixed as of https://github.com/vertcoin/vertcoin/commit/a1082b34719c93a753695032a0e222d98a75d6b6
