### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by elzorrorebelde** [vertcoin/vertcoin-old#49]
I got an error while compiling:

```
/usr/include/boost/variant/get.hpp: In instantiation of 'typename boost::add_reference<T>::type boost::strict_get(boost::variant<T0, TN ...>&) [with U = const CScriptID&; T0 = CNoDestination; TN = {CKeyID, CScriptID}; typename boost::add_reference<T>::type = const CScriptID&]':
/usr/include/boost/variant/get.hpp:284:33:   required from 'typename boost::add_reference<T>::type boost::get(boost::variant<T0, TN ...>&) [with U = const CScriptID&; T0 = CNoDestination; TN = {CKeyID, CScriptID}; typename boost::add_reference<T>::type = const CScriptID&]'
src/rpcrawtransaction.cpp:242:77:   required from here
/usr/include/boost/variant/get.hpp:212:5: error: static assertion failed: boost::variant does not contain specified type U, call to boost::get<U>(boost::variant<T...>&) will always throw boost::bad_get exception
     BOOST_STATIC_ASSERT_MSG(
     ^
Makefile:2199: recipe for target 'build/rpcrawtransaction.o' failed
make: *** [build/rpcrawtransaction.o] Error 1
```

I have boost 1.58.0 installed.

**Comment by rhkarls** [comment]
"Changing line 242 in src/rpcrawtransaction.cpp to "const CScriptID& hash = boost::get<CScriptID>(address);" fixes this (same as bitcoin fix). Perhaps this is something to consider for supporting newer boost versions?"
See http://www.reddit.com/r/vertcoin/comments/372ydk/wallet_crashes_on_os_x_1075/crjk8gs and https://github.com/bitcoin/bitcoin/pull/6114/files

**Comment by metalicjames** [comment]
Indeed, I have pushed the fix to master. Thanks for showing me this fix.

**Comment by elzorrorebelde** [comment]
Awesome! Thank you very much!

James Lovejoy writes:

> Indeed, I have pushed the fix to master. Thanks for showing me this fix. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vertcoin/vertcoin/issues/49#issuecomment-105074266

## 

Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra
