### ISSUE TITLE
listaccounts returning invalid number.

### ISSUE THREAD

**Issue by miningpoolhub** [vertcoin/vertcoin-old#55]
When I type "vertcoind listaccounts"
it shows
{
"" : -20686.04748736
}

I have "" (empty string) account and it should show a positive number.
I get correct result from "vertcoind getbalance" command.

This was working well before the hardfork update. Maybe something's broken.

**Comment by metalicjames** [comment]
Is this still a problem? There have been no other reports of it and I have not experienced it myself.

**Comment by metalicjames** [comment]
I cannot reproduce this bug so I am assuming this issue is closed for now.
