### ISSUE TITLE
Clients < 10.0 should be disconnected

### ISSUE THREAD

**Issue by mmouse-** [vertcoin/vertcoin-old#62]
Because of the hardfork clients < v10.0 are stuck on the wrong chain. They keep downloading the same blocks on and on and waste lots of bandwidth on uptodate nodes.

From getpeerinfo on my node:
`{
        "addr" : "218.93.205.123:58466",
        "services" : "00000003",
        "lastsend" : 1456074613,
        "lastrecv" : 1456074572,
        "bytessent" : 3615274562,
        "bytesrecv" : 205288091,
        "blocksrequested" : 2,
        "conntime" : 1455803836,
        "version" : 70002,
        "subver" : "/Satoshi:0.9.0.2/",
        "inbound" : true,
        "startingheight" : 363666,
        "banscore" : 0
    },
`
And this is just one example peer.

**Comment by metalicjames** [comment]
Done
