### ISSUE TITLE
wallet does not run in Windows 10

### ISSUE THREAD

**Issue by newmzy** [vertcoin/vertcoin-old#63]
Hi there, I just got interested in Vertcoin, possibly to mine it. I downloaded the Win64 latest binary, ran it, allowed it in the firewall. I see a command prompt open for a couple of seconds then close. I guess I will try running it in the command prompt myself instead of double clicking to see if it gives me more info....

**Comment by metalicjames** [comment]
Did you use vertcoind or the graphical wallet? Could you attach a copy of the log file located at "%appdata%/Vertcoin/debug.log"?

**Comment by newmzy** [comment]
I'm sorry, I didn't even realize there was a graphical wallet. I think I just followed a link from the vertcoin page and it pointed me to the latest release of vertcoind.

I will now try to find the graphical wallet!

**Comment by newmzy** [comment]
OK now I realize my mistake - I have downloaded vertcoin-qt and it's syncing the blockchain.

Sorry to waste your time!
