### ISSUE TITLE
VTC wallet v 0.10.0.1 windows not syncing

### ISSUE THREAD

**Issue by uakhan23** [vertcoin/vertcoin-old#64]
i have downloaded the titled version and it is just not syncing... im starting to hate this wallet. can anyone help me

**Comment by metalicjames** [comment]
Hi,

Sorry about this, clearly the node list needs updating. In the meantime, you can go to help->debug window->console and type "addnode 5.196.74.100 onetry" and the wallet should start syncing.

James

**Comment by uakhan23** [comment]
thank you so much james, its syncing after entering this command

umair
