### ISSUE TITLE
I did not see portable binaries at vertcoin.org

### ISSUE THREAD

**Issue by Altoidnerd** [vertcoin/vertcoin-old#7]
I love portable versions as I run many nodes for many coins.  

For use on ubuntu/debian: Is there a tarball somewhere, or must I build from source?  

For my windows machines: us paranoids don't run .exe files, ever.

Building bitcoind is actually not all that trivial.  Binaries would be nice.

Good work good coin.

**Comment by erkmos** [comment]
We have an Ubuntu PPA for 12.04, 12.10, 13.10 and 14.04 (it's listed on vertcoin.org)
sudo add-apt-repository ppa:vertcoin/ppa
sudo apt-get update
sudo apt-get install vertcoin

replace install vertcoin with vertcoind or vertcoin-qt if you just want one of them
