### ISSUE TITLE
libmemenv.a could not read symbols: Archive has no index; run ranlib to add one

### ISSUE THREAD

**Issue by iScrypt** [vertcoin/vertcoin-old#9]
Hello

i m getting this error while compiling

"libmemenv.a could not read symbols: Archive has no index; run ranlib to add one"

any idea how to solve this

**Comment by Paul-Bradley** [comment]
Hi,

Strange, I have built several times from the current git (including today)
without issues, but this sounds like a stale object file. Try to

make -f makefile.unix clean

Then build again. Let me know if you still have issues.

Thanks

**Comment by erkmos** [comment]
Closing this as it appears to be an isolated case.
